server:
  port: 8081

spring:
  application:
    name: foreign-exchange
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

frankfurter:
  client:
    url: https://api.frankfurter.dev/v2
    connect-timeout: 2s
    read-timeout: 3s

cache:
  currency-rate-pair:
    ttl: 3600s
    max-size: 1000
