CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT clients_client_id UNIQUE (client_id)
);

CREATE TABLE balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients (id),
    currency VARCHAR(3) NOT NULL,
    amount NUMERIC(19, 4) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT balances_client_currency UNIQUE (client_id, currency),
    CONSTRAINT balances_currency_iso CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT balances_amount_non_negative CHECK (amount >= 0)
);

CREATE TABLE conversions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id UUID NOT NULL,
    client_id BIGINT NOT NULL REFERENCES clients (id),
    source_currency VARCHAR(3) NOT NULL,
    source_amount NUMERIC(19, 4) NOT NULL,
    target_currency VARCHAR(3) NOT NULL,
    target_amount NUMERIC(19, 4) NOT NULL,
    rate NUMERIC(19, 8) NOT NULL,
    idempotency_key VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT conversions_transaction_id UNIQUE (transaction_id),
    CONSTRAINT conversions_source_currency_iso CHECK (source_currency ~ '^[A-Z]{3}$'),
    CONSTRAINT conversions_target_currency_iso CHECK (target_currency ~ '^[A-Z]{3}$'),
    CONSTRAINT conversions_amounts_and_rate_positive
        CHECK (source_amount > 0 AND target_amount > 0 AND rate > 0)
);

CREATE UNIQUE INDEX conversions_client_idempotency_key
    ON conversions (client_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE INDEX ix_conversions_client_created_at ON conversions (client_id, created_at DESC);

CREATE INDEX ix_conversions_created_at ON conversions (created_at);
